[tool.poetry]
name = "async-python-sprint-2"
version = "0.1.0"
description = ""
authors = ["Александр Видяков  <alex.vidyakov@yandex.ru>"]
readme = "README.md"
packages = [{include = "async_python_sprint_2"}]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.1.3"
loguru = "^0.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
